CREATE DATABASE DDL_UTS

USE DDL_UTS

CREATE TABLE BorrowerData(
MemberNum CHAR(5) PRIMARY KEY CHECK(MemberNum LIKE 'MN[0-9][0-9][0-9]'),
FullName VARCHAR(50) NOT NULL,
[Address] VARCHAR(50) NOT NULL,
BirthDate DATE NOT NULL,
Email VARCHAR(50) NOT NULL,
PhoneNumber VARCHAR(50) NOT NULL
)
SELECT * FROM BorrowerData

CREATE TABLE BorrowerBook(
BookCode CHAR(5) PRIMARY KEY CHECK (BookCode LIKE 'BC[0-9][0-9][0-9]'),
BookTitle VARCHAR(50) NOT NULL,
MemberNum CHAR(5) FOREIGN KEY REFERENCES BorrowerData(MemberNum) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
)
SELECT * FROM BorrowerBook

CREATE TABLE BookDetail(
BookCode CHAR(5) FOREIGN KEY REFERENCES BorrowerBook(BookCode) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
BorrowedDate DATE NOT NULL,
Duration INT NOT NULL,
ReturnedDate date NOT NULL,
Due VARCHAR(5) NOT NULL,
Penalty INT
)
SELECT * FROM BookDetail